name: Python Tests

# When to run tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    # Step 1: Check out code
    - uses: actions/checkout@v3
    
    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    # Step 3: Run tests
    - name: Run test suite
      run: |
        echo "Running tests..."
        python testing.py
    
    # Step 4: Show test results
    - name: Display test status
      if: always()
      run: |
        if python testing.py > /dev/null 2>&1; then
          echo "✅ All tests passed!"
        else
          echo "❌ Some tests failed"
          exit 1
        fi